# Generated by Django 4.2.7 on 2023-11-29 21:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=100, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('category', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('CREDIT_CARD_EXPENSE', 'Credit Card Expense')], max_length=20)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='tags.tag')),
            ],
        ),
    ]
