# Generated by Django 4.2.7 on 2023-11-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tags',
            new_name='tag',
        ),
    ]
