# Generated by Django 4.2.7 on 2023-11-27 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_tags_transaction_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 21, 0, 0, 344624, tzinfo=datetime.timezone.utc)),
        ),
    ]
