# Generated by Django 4.2.7 on 2024-01-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_month_year_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='month_year_reference',
            field=models.CharField(max_length=6),
        ),
    ]
