# Generated by Django 4.2.7 on 2024-01-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_month_year_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='month_year_reference',
            new_name='year_month_reference',
        ),
    ]
