# Generated by Django 4.2.7 on 2024-01-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_month_year_reference_transaction_year_month_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='year_month_reference',
            field=models.CharField(max_length=7),
        ),
    ]
