# Generated by Django 4.2.7 on 2023-12-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(choices=[('Casa', 'Casa'), ('Alimentacao', 'Alimentacao'), ('Saude', 'Saude'), ('Assinaturas', 'Assinaturas'), ('Transporte', 'Transporte'), ('Educacao', 'Educacao'), ('Pet', 'Pet'), ('Lazer', 'Lazer'), ('Outros', 'Outros')], max_length=70)),
                ('sub_tag_name', models.CharField(max_length=100)),
            ],
        ),
    ]
