# Generated by Django 4.2.7 on 2024-02-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('Account', 'Account'), ('Credit', 'Credit Card')], max_length=30),
        ),
    ]
