# Generated by Django 4.2.7 on 2024-02-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['id']},
        ),
    ]
